version: '3.4'

services:
  inmemoryidentityappblazor:
    image: fluffybunny/inmemoryidentityappblazor:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7000:80
      - 7001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7001
 